import hashlib
import os
import tempfile
from subprocess import Popen, PIPE


def string_to_hash(string):
    bytes = string.encode()
    hash_object = hashlib.md5(bytes)
    return hash_object.hexdigest()


def remove_tmp_files():
    """ remove invalid files generated by fuzzers """
    temp_dir = tempfile.gettempdir()
    tmp_files = [
        os.path.join(temp_dir, fuzz_file.strip())
        for fuzz_file in os.listdir(temp_dir)
        if 'fuzz' in fuzz_file or 'temp_' in fuzz_file
    ]
    for tmp in tmp_files:
        try:
            os.remove(tmp)
        except:
            pass


def kill_processes():
    ''' killing hanging process '''
    proc = Popen(["pkill", "-f", "jsvu"], stdout=PIPE)
    proc.wait()
